In [1]:
import os
import pandas as pd
from collections import defaultdict

In [22]:
import os
import pandas as pd

DATASET_DIR = "../dataset"

data = []

for source in ["public", "local" ]:
    source_path = os.path.join(DATASET_DIR, source)

    if not os.path.exists(source_path):
        continue

    for cls in os.listdir(source_path):
        cls_path = os.path.join(source_path, cls)

        if not os.path.isdir(cls_path):
            continue

        count = len([
            f for f in os.listdir(cls_path)
            if os.path.isfile(os.path.join(cls_path, f))
        ])

        data.append({
            "class": cls,
            "source": source,
            "jumlah": count
        })

df = pd.DataFrame(data)

table_dataset = df.pivot_table(
    index="class",
    columns="source",
    values="jumlah",
    fill_value=0
)

table_dataset["total"] = table_dataset.sum(axis=1)
table_dataset.loc["TOTAL"] = table_dataset.sum()

print("\n📂 DATASET")
table_dataset

📂 DATASET

source       local  public   total
class
alur          68.0    27.0    95.0
lubang        63.0   558.0   621.0
retak         34.0   209.0   243.0
tidak_rusak   24.0    46.0    70.0
TOTAL        189.0   840.0  1029.0

In [43]:
MERGED_DIR = "../dataset_merged"

data = []

for cls in os.listdir(MERGED_DIR):
    cls_path = os.path.join(MERGED_DIR, cls)

    if not os.path.isdir(cls_path):
        continue

    count = len([
        f for f in os.listdir(cls_path)
        if os.path.isfile(os.path.join(cls_path, f))
    ])

    data.append({
        "class": cls,
        "jumlah": count
    })

df = pd.DataFrame(data).sort_values("class")

print("\n📂 DATASET MERGED")
df

📂 DATASET MERGED

         class  jumlah
0         alur      95
1       lubang     621
2        retak     243
3  tidak_rusak      70

In [4]:
MERGED_DIR = "../dataset_merged_aug"

data = []

for cls in os.listdir(MERGED_DIR):
    cls_path = os.path.join(MERGED_DIR, cls)

    if not os.path.isdir(cls_path):
        continue

    count = len([
        f for f in os.listdir(cls_path)
        if os.path.isfile(os.path.join(cls_path, f))
    ])

    data.append({
        "class": cls,
        "jumlah": count
    })

df = pd.DataFrame(data).sort_values("class")

print("\n📂 DATASET MERGED")
df

📂 DATASET MERGED

         class  jumlah
0         alur     597
1       lubang     621
2        retak     621
3  tidak_rusak     621

In [45]:
SPLIT_DIR = "../dataset_split"

data = []

for split in ["train", "val", "test"]:
    split_path = os.path.join(SPLIT_DIR, split)

    if not os.path.exists(split_path):
        continue

    for cls in os.listdir(split_path):
        cls_path = os.path.join(split_path, cls)

        if not os.path.isdir(cls_path):
            continue

        count = len([
            f for f in os.listdir(cls_path)
            if os.path.isfile(os.path.join(cls_path, f))
        ])

        data.append({
            "class": cls,
            "split": split,
            "jumlah": count
        })

df = pd.DataFrame(data)

table_split = df.pivot_table(
    index="class",
    columns="split",
    values="jumlah",
    fill_value=0
)

table_split["total"] = table_split.sum(axis=1)

print("\n📂 DATASET SPLIT")
table_split

📂 DATASET SPLIT

split        test  train   val  total
class
alur         10.0   76.0   9.0   95.0
lubang       63.0  496.0  62.0  621.0
retak        25.0  194.0  24.0  243.0
tidak_rusak   7.0   56.0   7.0   70.0

In [47]:
SPLIT_DIR = "../dataset_split_aug"

data = []

for split in ["train", "val", "test"]:
    split_path = os.path.join(SPLIT_DIR, split)

    if not os.path.exists(split_path):
        continue

    for cls in os.listdir(split_path):
        cls_path = os.path.join(split_path, cls)

        if not os.path.isdir(cls_path):
            continue

        count = len([
            f for f in os.listdir(cls_path)
            if os.path.isfile(os.path.join(cls_path, f))
        ])

        data.append({
            "class": cls,
            "split": split,
            "jumlah": count
        })

df = pd.DataFrame(data)

table_split = df.pivot_table(
    index="class",
    columns="split",
    values="jumlah",
    fill_value=0
)

table_split["total"] = table_split.sum(axis=1)
table_split.loc["TOTAL"] = table_split.sum()

print("\n📂 DATASET SPLIT")
table_split

📂 DATASET SPLIT

split         test   train    val   total
class
alur          61.0   477.0   59.0   597.0
lubang        63.0   496.0   62.0   621.0
retak         63.0   496.0   62.0   621.0
tidak_rusak   63.0   496.0   62.0   621.0
TOTAL        250.0  1965.0  245.0  2460.0